### ISSUE TITLE
cloudstack-setup-databases is failing on Ubuntu 22.04

### ISSUE THREAD

**Issue by kiranchavala** [shapeblue/hackerbook#13] opened 2023-01-27 12:05 UTC
root@kiran-mgmt:~# cloudstack-setup-databases cloud:cloud@localhost  --deploy-as=root: -i 192.168.122.10
Traceback (most recent call last):
  File "/usr/bin/cloudstack-setup-databases", line 45, in <module>
    from cloud_utils import check_selinux, CheckFailed, resolves_to_ipv6
ImportError: cannot import name 'check_selinux' from 'cloud_utils' (/usr/lib/python3/dist-packages/cloud_utils.py)

Code : 
https://github.com/apache/cloudstack/blob/main/setup/bindir/cloud-setup-databases.in

**Comment by kiranchavala** [comment] 2023-01-27 12:06
No issues on Ubuntu 20.04 LTS

**Comment by rohityadavcloud** [comment] 2023-01-27 12:08
@kiranchavala this may be a cloudstack issue (or mysql server setup issue). Could you confirm and raise it upstream at https://github.com/apache/cloudstack You can discuss with Wei or Daan about this.

**Comment by kiranchavala** [comment] 2023-01-27 12:12
Sure

Similar issue was raised in the past, but that was with mariadb+galera and it was closed without any resolution

https://github.com/apache/cloudstack/issues/6763

**Comment by rohityadavcloud** [comment] 2023-01-27 12:15
@kiranchavala as I said you may double check your env, if you believe this is an issue pl re-open that issue or log a new one. cc @weizhouapache @DaanHoogland

**Comment by weizhouapache** [comment] 2023-01-27 12:39
@kiranchavala 
you need to turn off  sql_require_primary_key

```
mysql> show variables like "sql_require_primary_key";
+-------------------------+-------+
| Variable_name           | Value |
+-------------------------+-------+
| sql_require_primary_key | OFF   |
+-------------------------+-------+
1 row in set (0.00 sec)
```

**Comment by rohityadavcloud** [comment] 2023-01-27 12:40
is that a known issue @weizhouapache in which should we document/update in hackebook and upstream docs? cc @kiranchavala @DaanHoogland

**Comment by weizhouapache** [comment] 2023-01-27 12:50
> is that a known issue @weizhouapache in which should we document/update in hackebook and upstream docs? cc @kiranchavala @DaanHoogland

@rohityadavcloud 
the variable is OFF by default. Not sure if we need to emphasize it.

let's wait @kiranchavala to confirm if it is a root cause.

**Comment by weizhouapache** [comment] 2023-01-27 15:03
> Hi @weizhouapache @rohityadavcloud
> 
> It's probably a vm environment or a config issue
> 
> I Deployed a new ubuntu 22.04 vm and its working fine without any issues

thanks for the update @kiranchavala 
closing it

**Closed** 2023-01-27 15:02 UTC
